### ISSUE TITLE
Where I should put a validate method for Post struct?

### ISSUE THREAD

**Issue by dashaus** [sourcegraph/thesrc#13]
Hi!,
I'm following this pattern, and I have a doubt... I want add a **Validate** method for validate the data before insert it in the database. I should put it as method for the **Posts** struct or **postsStore** struct?

Thanks for sharing this skeleton, is really useful!!

**Comment by sqs** [comment]
Maybe as a method on Post (the model) or a separate func. Its implementation isn't specific to the data store (sql/whatever) and you probably don't need to mock it. So both Posts and postsStore are out. If it doesn't use any live data, then a method would be easy. If it does, perhaps a func that takes a Post to validate and a Posts to look up live data to validate the Post.

**Comment by dashaus** [comment]
Oh, I mean say Post struct instead of Posts struct... 

All the "validate" functions validate data from html form, and occasionally, it access to database for validate some data concrete, so I think that it fit as a method according as you comment.

Thanks you!!

**Comment by sqs** [comment]
Cool!

If you want to submit a PR with some validation functions to this repo (when you find a good way to do it in your own code), that would be awesome. :+1:
