### ISSUE TITLE
can't seem to connect this to a heroku postgresql db

### ISSUE THREAD

**Issue by ghost** [sourcegraph/thesrc#15]
not sure what I'm missing, I tried feeding the correct url into datastore/db.go  but to no avail. 

Should I be editing somewhere else as well? it seems to always prefer a local postgres instance...

**Comment by sqs** [comment]
Did you set the `PG*` env vars? (PGUSER, PGPASSWORD, PGHOST, etc.)

**Comment by ghost** [comment]
Hi Sqs. Thanks for replying, not sure what changed but I reset the  PG\*  variables (inside of .env and inside of the fish shell config.fish file) this morning, and everything works great!
