### ISSUE TITLE
Misleading repository description 

### ISSUE THREAD

**Issue by remisb** [sourcegraph/thesrc#16]
On the repository description a broken link to https://sourcegraph.com/sourcegraph/thesrc should be replaced with the correct one https://sourcegraph.com/github.com/sourcegraph/thesrc :) .

**Comment by dmitshur** [comment]
You're absolutely right, thanks for reporting this. I've updated it to the right URL.

This repository has not been updated recently, so it's possible there may be some other things that will require similar updating.

Thanks again!
